export const Array = [
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/dune2/1280/720",
    "genre": ["Sci-Fi", "Adventure"],
    "language": "English",
    "title": "Dune: Part Two",
    "posterImageUrl": "https://lh5.googleusercontent.com/proxy/q7mgmXWoSr_1m98zzme9c8hxAlq7y8tmHcU0Kc5V8ohCVAMU2e6urV0XyXHTwSbNZJRb-V6iEbPRbczWzO-2UNbRpIcVA3qoGSAZGFcmoD8",
    "releaseDate": "2024-02-27",
    "averageRating": 8.2,
    "overallRatingCount": 4685,
    "overview": "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    "trailerId": "U2Qp5pL3ovA"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/jawan/1280/720",
    "genre": ["Action", "Thriller"],
    "language": "Hindi",
    "title": "Jawan",
    "posterImageUrl": "https://i.pinimg.com/736x/59/27/50/5927501eeb30666518c6b9fa309fc4be.jpg",
    "releaseDate": "2023-09-07",
    "averageRating": 7.0,
    "overallRatingCount": 989,
    "overview": "A man is driven by a personal vendetta to rectify the wrongs in society, while keeping a promise made years ago.",
    "trailerId": "COv52Qyctws"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/oppenheimer/1280/720",
    "genre": ["Drama", "History"],
    "language": "English",
    "title": "Oppenheimer",
    "posterImageUrl": "https://upload.wikimedia.org/wikipedia/donate/5/5b/Oppenheimer_poster.jpg",
    "releaseDate": "2023-07-19",
    "averageRating": 8.1,
    "overallRatingCount": 8753,
    "overview": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    "trailerId": "uYPbbksJxIg"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/kalki/1280/720",
    "genre": ["Sci-Fi", "Adventure", "Action"],
    "language": "Telugu",
    "title": "kalki 2898 AD",
    "posterImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzjcxwdar3BK__mmBBc_x7cNxvkmC96ciZaBfyxemeSTAtEqE_KILUfxo&s=10",
    "releaseDate": "2024-06-27",
    "averageRating": 7.4,
    "overallRatingCount": 165,
    "overview": "In a dystopian future, a bounty hunter embarks on a mission to capture a pregnant woman whose child is prophesied to be a divine incarnation.",
    "trailerId": "kQDd1AhGIHk"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/insideout2/1280/720",
    "genre": ["Animation", "Family", "Comedy"],
    "language": "English",
    "title": "Inside Out 2",
    "posterImageUrl": "https://upload.wikimedia.org/wikipedia/en/f/f7/Inside_Out_2_poster.jpg",
    "releaseDate": "2024-06-11",
    "averageRating": 7.7,
    "overallRatingCount": 1941,
    "overview": "Follow Riley in her teenage years, where she encounters new emotions like Anxiety, Envy, and Embarrassment.",
    "trailerId": "LEjhY15eCx0"
  },
  {
    "adult": true,
    "backgroundImageUrl": "https://picsum.photos/seed/pulpfiction/1280/720",
    "genre": ["Crime", "Thriller"],
    "language": "English",
    "title": "Pulp Fiction",
    "posterImageUrl": "https://m.media-amazon.com/images/I/41pTAnSCW-S.jpg",
    "releaseDate": "1994-09-10",
    "averageRating": 8.9,
    "overallRatingCount": 27289,
    "overview": "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "trailerId": "s7EdQ4FqbhY"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/shawshank/1280/720",
    "genre": ["Drama", "Crime"],
    "language": "English",
    "title": "The Shawshank Redemption",
    "posterImageUrl": "https://m.media-amazon.com/images/I/510e5vuv4JL._UF894,1000_QL80_.jpg",
    "releaseDate": "1994-09-23",
    "averageRating": 9.3,
    "overallRatingCount": 26310,
    "overview": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "trailerId": "PLl99DlL6b4"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/spiritedaway/1280/720",
    "genre": ["Animation", "Family", "Fantasy"],
    "language": "Japanese",
    "title": "Spirited Away",
    "posterImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJvKiFkcncG1fy13gFQGgz-U9K5oSyqcwOehpJu-h_TXtJkoYR65FdIDS4&s=10",
    "releaseDate": "2001-07-20",
    "averageRating": 8.5,
    "overallRatingCount": 16049,
    "overview": "A 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
    "trailerId": "ByXuk9QqQkk"
  },
  {
    "adult": false,
    "backgroundImageUrl": "https://picsum.photos/seed/endgame/1280/720",
    "genre": ["Adventure", "Sci-Fi", "Action"],
    "language": "English",
    "title": "Avengers: Endgame",
    "posterImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-pYmRoP7vBkXPxY7Bv-A5p07aL4WTUjnyaGURmAoks2sXyywiVNM2QWW2&s=10",
    "releaseDate": "2019-04-24",
    "averageRating": 8.4,
    "overallRatingCount": 12234,
    "overview": "The remaining Avengers must assemble to reverse the devastating events caused by Thanos and restore balance to the universe.",
    "trailerId": "TcMBFSGVi1c"
  },
    {
      "adult": false,
      "backgroundImageUrl": "https://picsum.photos/seed/forrestgump/1280/720",
      "genre": ["Comedy", "Drama", "Romance"],
      "language": "English",
      "title": "Forrest Gump",
      "posterImageUrl": "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
      "releaseDate": "1994-06-23",
      "averageRating": 8.8,
      "overallRatingCount": 22108,
      "overview": "A man with a low IQ has witnessed some of the most important events in US history, but all he wants is to be with his childhood sweetheart.",
      "trailerId": "uPIEn0M8su0"
    },
    {
      "adult": true,
      "backgroundImageUrl": "https://picsum.photos/seed/godfather/1280/720",
      "genre": ["Drama", "Crime"],
      "language": "English",
      "title": "The Godfather",
      "posterImageUrl": "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
      "releaseDate": "1972-03-14",
      "averageRating": 9.2,
      "overallRatingCount": 19875,
      "overview": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      "trailerId": "UaVTIH8mujA"
    },
    {
      "adult": false,
      "backgroundImageUrl": "https://picsum.photos/seed/matrix/1280/720",
      "genre": ["Action", "Sci-Fi"],
      "language": "English",
      "title": "The Matrix",
      "posterImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRdSxsRUNxd0O_0u1Wi0Nfj-om44cVLQe-EiiDcOpgESaIDd8SbIlYjOuo&s=10",
      "releaseDate": "1999-03-30",
      "averageRating": 8.7,
      "overallRatingCount": 20112,
      "overview": "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.",
      "trailerId": "vKQi3bBA1y8"
    },
    {
      "adult": false,
      "backgroundImageUrl": "https://picsum.photos/seed/baahubali2/1280/720",
      "genre": ["Action", "Drama", "Fantasy"],
      "language": "Telugu",
      "title": "Baahubali 2: The Conclusion",
      "posterImageUrl": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p14612810_p_v8_aa.jpg",
      "releaseDate": "2017-04-27",
      "averageRating": 8.2,
      "overallRatingCount": 978,
      "overview": "Shiva, the son of Baahubali, learns about his heritage and the events that transpired in the Mahishmati Kingdom.",
      "trailerId": "G62HrubdD6o"
    },
    {
      "adult": false,
      "backgroundImageUrl": "https://picsum.photos/seed/dangal/1280/720",
      "genre": ["Action", "Drama", "Biography"],
      "language": "Hindi",
      "title": "Dangal",
      "posterImageUrl": "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
      "releaseDate": "2016-12-21",
      "averageRating": 8.3,
      "overallRatingCount": 1980,
      "overview": "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games.",
      "trailerId": "x_7YlGv9u1g"
    },
    {
      "adult": true,
      "backgroundImageUrl": "https://picsum.photos/seed/animal/1280/720",
      "genre": ["Action", "Crime", "Drama"],
      "language": "Hindi",
      "title": "Animal",
      "posterImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjY7v8wF4k5wm6codDWB5TYg3-iwBIGhaUhWb-131-dsGWD09HGK8m984D&s=10", 
      "releaseDate": "2023-12-01",
      "averageRating": 6.3,
      "overallRatingCount": 754,
      "overview": "The son of a wealthy industrialist returns home after a tragedy, leading him down a path of violent revenge and self-destruction.",
      "trailerId": "8FkLRUJj-o0"
    },
    {
      "adult": false,
      "backgroundImageUrl": "https://picsum.photos/seed/pushpa/1280/720",
      "genre": ["Action", "Drama", "Crime"],
      "language": "Telugu",
      "title": "Pushpa: The Rise",
      "posterImageUrl": "https://lh6.googleusercontent.com/proxy/rh3TDR2VKKvyqZLqp-VgZqoTPxMpc3RiEm9bC-pWc2yBMPo3tY6tUSiksmzopcGtaF83S_ipPiQo77203eewqpisylJ6RTaOHwpSlMQ1nIEsH0TT3X2wCLiaTkoucVtMYKPvB9c",
      "releaseDate": "2021-12-17",
      "averageRating": 7.6,
      "overallRatingCount": 1800,
      "overview": "A labourer rises through the ranks of a red sandalwood smuggling syndicate, making enemies and earning notoriety along the way.",
      "trailerId": "Q1NKMPhP8PY"
    }  
]